"use strict";
// import { ExtractSlotCardFromHTML } from "./ExtractSlotCardFromHTML"
exports.__esModule = true;
var GenerateBuildData_1 = require("./GenerateBuildData");
var Utils_NodeJS_1 = require("./Utils_NodeJS");
// const text = '<div id="d4tools-tooltip-root"><div class="d4tools-tooltip"><div class="d4-tooltip-positioner d4-tooltip-visible d4-tooltip-bottom" style="pointer-events: auto; left: 159px; top: 275.5px;"><div class="d4t-GameTooltip d4t-tip-rare"><div class="d4t-top-right-icon" style="background-image: url(&quot;https://assets-ng.maxroll.gg/d4-tools/images/webp/3235777746.webp&quot;);"></div><div class="d4t-tip-header d4-color-rare"><div class="d4t-title">Mental Crown</div><div class="d4t-sub-title">Rare Helm</div><div class="d4-color-gray">400 Item Power</div></div><div class="d4t-separator d4t-left"></div><div class="d4t-armor">500 Armor</div><ul><li class="d4t-list-affix d4-color-gray">4.5% Cooldown Reduction<span class="d4-color-inactive"> [1.8 - 3.0]%</span></li><li class="d4t-list-affix d4-color-gray">+4.5% Basic Skill Attack Speed <span class="d4-color-inactive"> [2.1 - 4.5]%</span></li><li class="d4t-list-affix d4-color-gray">+2 Ranks of Hydra (Sorcerer Only)<span class="d4-color-inactive"> [1 - 2]</span></li></ul><div class="d4t-socket"><div class="d4t-slot"><div class="d4t-gems-icon" style="background-position: -13em 0em;"></div></div><div class="d4t-effect">2.5% Maximum Life</div></div><div class="d4t-separator"></div></div></div></div></div>'
// const text = '<div class="d4t-GameTooltip d4t-tip-legendary"><div class="d4t-top-right-icon" style="background-image: url(&quot;https://assets-ng.maxroll.gg/d4-tools/images/webp/892429542.webp&quot;);"></div><div class="d4t-tip-header d4-color-legendary"><div class="d4t-title">Archon Helm of Might</div><div class="d4t-sub-title">Ancestral Legendary Helm</div><div class="d4-color-gray">800+25 Item Power</div><div><span class="d4t-upgrade-icon"></span>Upgrades: 5/5</div></div><div class="d4t-separator d4t-left"></div><div class="d4t-armor">1,031 Armor</div><ul><li class="d4t-list-affix d4-color-gray">10.3% Cooldown Reduction<span class="d4-color-inactive"> [6.2 - 10.3]%</span></li><li class="d4t-list-affix d4-color-gray">+15.0% Basic Skill Attack Speed <span class="d4-color-inactive"> [6.6 - 15.0]%</span></li><li class="d4t-list-affix d4-color-gray">+1,211 Maximum Life<span class="d4-color-inactive"> [559 - 1,211]</span></li><li class="d4t-list-affix d4-color-gray">+15.0% Lucky Hit Chance while You Have a Barrier<span class="d4-color-inactive"> [6.6 - 15.0]%</span></li><li class="d4t-list-star d4-color-legendary"><span class="d4-color-important">Basic</span> Skills grant <span class="d4-color-number">20%</span> Damage Reduction for <span class="d4-color-random">6.0<span class="d4-color-inactive"> [2.0 - 6.0]</span></span> seconds.</li><div class="d4t-description">Aspect unlocked by completing<div class="d4-font-icon d4-icon-1741287201" style="font-size: 2.5em;"></div><span class="d4-color-important">Dark Ravine</span> in <span class="d4-color-important">Dry Steppes</span></div></ul><div class="d4t-socket"><div class="d4t-slot"><div class="d4t-gems-icon" style="background-position: 0em -1em;"></div></div><div class="d4t-effect">4.0% Maximum Life</div></div><div class="d4t-separator"></div></div>'
// console.log(ExtractSlotCardFromHTML(text))
var res = (0, GenerateBuildData_1.GenerateBuildData)();
if (typeof res === 'string')
    (0, Utils_NodeJS_1.LogRed)('error: ' + res);
// else
//     console.log(JSON.stringify(res, null, 1));
